package br.dev.extdigisac.domain;

public enum ErrorCode {
    TENANT_NOT_FOUND,
    TENANT_PENDING,
    TENANT_BLOCKED,
    LICENSE_EXPIRED,
    CREDENTIAL_INVALID,
    UNAUTHENTICATED,
    TOKEN_EXPIRED,
    FORBIDDEN,
    NO_PERMISSION_RULE,
    DUPLICATE_CONTACT,
    OPEN_TICKET_EXISTS,
    EXTENSION_OUTDATED,
    RATE_LIMITED,
    UPSTREAM_ERROR,
    INVALID_HOST,
    ACCOUNT_MISMATCH,
    VALIDATION_ERROR,
    NOT_FOUND,
    INTERNAL_ERROR
}
